dist: trusty
sudo: required
language: php
php:
- 7.2
- 7.3
env:
  global:
  - CORE_BRANCH=stable18
  - APP_NAME=pdf_tailor
  matrix:
  - DB=sqlite
branches:
  only:
  - master
git:
  submodules: false
stages:
- test
- name: release
  if: NOT type IN (pull_request)
before_install:
- wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
- ". ./before_install.sh $APP_NAME $CORE_BRANCH $DB"
- nvm install 12
- nvm use 12
- cd ../server
- "./occ check"
- "./occ status"
- "./occ app:list"
- "./occ app:enable $APP_NAME"
- "./occ app:list"
- cd apps/$APP_NAME/
- npm install
script:
- sh -c "find . -name \*.php -exec php -l \"{}\" \;"
- cd ../../
- echo "Running Nextcloud Code Check 1"
- "./occ app:check-code $APP_NAME -c private -c strong-comparison"
- echo "Running Nextcloud Code Check 2"
- "./occ app:check-code $APP_NAME -c deprecation"
- cd apps/$APP_NAME/
- echo "Running PHP Unit Tests"
- cd tests/Unit
- phpunit --configuration phpunit.xml
- cd ../..
- echo "Running JavaScript/TypeScript Unit Tests"
- npm run lint && npm run test && npm run build
- echo "Sending Test Coverage to Codacy"
- npm run coverage
- cd ..
jobs:
  include:
  - stage: release
    php: 7.2
    before_install:
    - git clone --depth 1 -b $CORE_BRANCH https://github.com/nextcloud/server
    - cd server
    - git submodule update --init
    - cd ..
    - nvm install 12
    - nvm use 12
    - npm install
    before_script: skip
    script:
    - npm run build
    before_deploy:
    - git config --local user.name "janis91"
    - git config --local user.email "janiskoehr@icloud.com"
    - node ci/gitTag.js
    - "./ci/build_release.sh"
    - openssl aes-256-cbc -K $encrypted_2bfe8d42284c_key -iv $encrypted_2bfe8d42284c_iv -in pdf_tailor.key.enc -out pdf_tailor.key -d
    - "./server/occ integrity:sign-app --privateKey=$PWD/pdf_tailor.key --certificate=$PWD/pdf_tailor.crt --path=$PWD/release"
    - mv release pdf_tailor
    - tar cfz pdf_tailor.tar.gz pdf_tailor
    - rm -rf pdf_tailor/
    deploy:
      provider: releases
      skip_cleanup: true
	  overwrite: true
      api_key:
    	secure: G2ddgkevKIMhgF+YJFkLxPJAwX8S0Y4+YtzAOBBG6eBpXCkBiq3/rkGehOLmz9Rss3i477jbC/2Y+rpR1W4TXWQmflqjQgAoVPVC7RhUdZ2rdOQsy34A5F+fy/cgRQx/TLfA7wy0AAIQK8wkuWmlRQ3SweQGMmv0BEdO+NZGHIp3H01xO0S0uGArT+ikrooP4V1pOfJJQf03ZqCtZg6rEcuvybrLPXS3Fy/0mAdsxejHit8QQvodiim6PT+23K0ACqPC3d1clUmMkY+wsvOe8HHDKNtlWJA4Djh7zlUeIba8gaH2S+0X7+yp2d6N7OIuek8re0us85ZalQK8e10hm4wvd1bzwbxAKcJI0+xroIdWw6SEu30vW9a03P43zVMzG83SoHmZjFGyDIbGikSpS4B6p4Wbk3iKRjNrHnqZd2aOA/eFfcKRGtNFpIXEMg1FkZd3bI7awCV05l7zQ2d0HOACd+JGqpBSDHS9NVgEBBU2NqXb67rCDFP8/TRxiBRW1PphUuU+mTjl0ae6wsbOm9PCPI4E66AXdb5Al0Gsm4ZC4N8GhJcYXrqHWVDW8xrDTX+EPdoN69ZcpA1bWuWpr4MOxoVYDGiGirZZ2XC0h6j4XaJAIFEzaHGr7rO6BphZLWM0l+dvdboqD63Ds31uADfD8Kp3l0txBFd1+uq6S6I=
      file: pdf_tailor.tar.gz
      on:
        repo: janis91/pdf_tailor
        branch: master
    after_deploy:
    - "./ci/release_to_nextcloud.sh"
    - rm -f pdf_tailor.key
